### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by lamby** [goodform/RediSearch#2]
@natoscott  wrote:
> Just doing a goodform/RediSearch build here - noticed there's
> some build warnings which I think may be due to missing tags?
> 
> $ make -C ./src all
> [...]
> fatal: No names found, cannot describe anything.
> make -C trie
> fatal: No names found, cannot describe anything.
> $ git tag -l
> $
> 
> Could you push the original tags in, up to the last open release?

**Comment by lamby** [comment]
````
$ git tag --contains c516603c0705ccd14efc1623c4702cba63b8d262 | xargs git tag -d 
$ git push --tags
[…]
 * [new tag]         v1.0.4 -> v1.0.4
 * [new tag]         v1.0.5 -> v1.0.5
 * [new tag]         v1.0.6 -> v1.0.6
 * [new tag]         v1.0.7 -> v1.0.7
 * [new tag]         v1.0.8 -> v1.0.8
 * [new tag]         v1.0.9 -> v1.0.9
 * [new tag]         v1.1.0 -> v1.1.0
 * [new tag]         v1.2.0 -> v1.2.0
$
```

**Comment by natoscott** [comment]
@lamby CircleCI is now passing for RediSearch
